/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yh_NvdimmUtils */

#ifndef _Included_com_yh_NvdimmUtils
#define _Included_com_yh_NvdimmUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yh_NvdimmUtils
 * Method:    write
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_yh_NvdimmUtils_write
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
